title:             Michael McShinsky
email:             michael@mcshinsky.net
description:       Front-end Developer based in Utah specializing in UI/UX development and design with an emphasis in ReactJS
author:            Michael McShinsky
url:               "http://mcshinsky.net"
theme:             jekyll-theme-clean-blog

# Social Profiles
twitter_username:  mikemcshinsky
github_username:   mmcshinsky
linkedin_username: michaelmcshinsky

# Build settings
markdown:          kramdown
pagination:
paginate:          5
paginate_path:     "/posts/page:num/"

plugins:
  - jekyll-feed
  - jekyll-paginate
