---
title: Michael McShinsky
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: michael@mcshinsky.net
description: Front-end Developer based in Utah specializing in UI/UX development and
  design with an emphasis in ReactJS
author: Michael McShinsky
url: http://mcshinsky.net
theme: jekyll-theme-clean-blog
twitter_username: mikemcshinsky
github_username: mmcshinsky
linkedin_username: michaelmcshinsky
markdown: kramdown
pagination: 
paginate: 5
paginate_path: "/posts/page:num/"
plugins:
- jekyll-feed
- jekyll-paginate
